name: Build

on: [push]

jobs:
  # FIXME: both build together?
  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: mstksg/get-package@v1
      with:
        apt-get: libc6-dbg
    - uses: actions/checkout@v1
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: try ls -l
      run: ./vg-in-place ls -l
    # TODO: block on gdbserver_tests/hgtls
    # - name: make regtest
    #   run: make regtest

  build_macos:

    runs-on: macos-latest

    steps:
    - uses: mstksg/get-package@v1
      with:
        brew: automake
    - uses: actions/checkout@v1
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: try ls -l
      run: ./vg-in-place ls -l
    # TODO: doesn't build
    # gcc -Winline -Wall -Wshadow -Wno-long-long -g -fno-stack-protector  -Wno-format-extra-args -Wno-literal-range -Wno-tautological-constant-out-of-range-compare -Wno-self-assign -Wno-string-plus-int -Wno-uninitialized -Wno-unused-value  -arch x86_64 -fPIC  -dynamic -dynamiclib -all_load -fpic  -o tls.so tls_so-tls_so.o `pwd`/tls2.so
    # Undefined symbols for architecture x86_64:
    #   "_global", referenced from:
    #       _test_so_global in tls_so-tls_so.o
    #      (maybe you meant: _test_so_global)
    # - name: make regtest
    #   run: make regtest
